# -*- coding: utf-8 -*-
"""Sistem Panen Olivia_TTS Bab 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10pUyocnkUAhfR4JrlNCsCKxr2HJBi7gS
"""

# hitung_panen.py
hasil_panen = []
n = int(input("Jumlah data panen: "))
for i in range(n):
    jumlah = float(input(f"Hasil panen ke-{i+1} (kg): "))
    hasil_panen.append(jumlah)

total = sum(hasil_panen)
print(f"Total hasil panen: {total} kg")
def hitung_diskon(total):
    if total >= 1000:
        return total * 0.10
    elif total >= 500:
        return total * 0.05
    return 0
